default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :generate_licences do
    generate_spm_licenses(
      workspace: "Example/Example.xcworkspace",
      destination: "Example/Example/Settings.bundle/Acknowledgements.plist"
    )
  end
end
